services:

  ollama:
    image: ollama/ollama:latest
    container_name: bsdi-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ollama serve &
        sleep 5
        ollama pull qwen3:4b
        wait

  app:
    build: .
    container_name: bsdi-app
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: qwen3:4b
    depends_on:
      - ollama

volumes:
  ollama_data: